### ISSUE TITLE
メッセージの送信に失敗したら同じメッセージが入るようにするべき

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#144]
https://twitter.com/#!/naru0ga/status/44943172207517696

ついでに要望書いとくか。@partakein って字数制限にかかってメッセージが送られなかったときにそのまま消えちゃうけど、取っておいて送信ウィンドウ再度開けたらそこから編集できるようにならないかな。それとももうなってる？<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=144</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
今となっては INVALID
