### ISSUE TITLE
*.partake.property に定義していある一部の属性を DB に移す

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#161]
*.partake.property を複数の環境で使うのはリスクがある。
release 用の *.partake.property と debug 用の *.partake.property は分けたい

DB 系のみ *.partake.property に定義すれば十分のはず。<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=161</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
今回の件で懲りたので、priority を上げます。
さっさとやりましょう。
