### ISSUE TITLE
javascript や css に version 番号つけるために、js や css の input タグを java 経由で吐かせるようにする。

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#166]
T/O<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=166</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p><p><strong>mayah@mayah.jp said, at 2012-03-25T03:07:26.000Z:</strong></p>

<p>minify もついでにしてほしい。</p>

**Comment by mayah** [comment]
DUPLICATED. See #308.
