### ISSUE TITLE
，開催日を修正した際に，リマインダーの日付に反映されない

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#167]
https://twitter.com/pk0612/status/64814152803295232
https://twitter.com/#!/pk0612/status/64913678897659904<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=167</p><hr/><h2>earlier comments</h2>

<p><strong>kawanaka.shinya said, at 2011-07-17T06:19:56.000Z:</strong></p>

<p>これはおかしいので直しましょう。なんでだ？</p>

**Comment by mayah** [comment]
あれから再現してないので一旦 close します。
