### ISSUE TITLE
@partakein につぶやくと勝手にイベントを作るとか

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#173]
RT されるとやばいけど。<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=173</p><hr/><h2>earlier comments</h2>

<p><strong>skypencil said, at 2011-05-18T15:50:21.000Z:</strong></p>

<p>@partakeinとかをフォローした状態で「JavaScript勉強会の開催が待たれる」などとつぶやくと「イベント立てました、あとはよろしく」とBOTが教えてくれるとか。別名「言い出しっぺの法則」機能。</p><p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
Too ambiguous. WONTFIX
