### ISSUE TITLE
参加ボタンをクリックしたのちに、ログインを要求する

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#179]
＜現状＞
参加・不参加ボタンの半透明画像と、「ログインしてください」という
文言が表示されている。

＜理想＞
ログインをしていなくても参加・不参加ボタンを押せる状況にし、
ボタンクリック後にログインを要求する。

[メリット]
初めての人にも使用方法がわかりやすい。直感的。<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=179</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
これは内部状態を過度に複雑にする上にあまりユーザーにとってのメリットがないのでしばらく対応しません。
