### ISSUE TITLE
`mvn test`でテストケースを全部回せるようにする

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#201]
テストケースを全て回すのが色々と面倒なので、Maven一発で全部実行できるようにする。
将来的にはCIサーバなどの導入も可能になるだろう。<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=201</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
Play 移行に伴い、mvn test は廃止されます。
WONTFIX

**Comment by KengoTODA** [comment]
Maven廃止後も`play test`で全テストケース実行したいなーと思っていますが、この認識は共有可能なものでしょうか、それとも他によりよい方法がありますでしょうか。
http://www.playframework.org/documentation/2.0.2/JavaTest
http://www.playframework.org/documentation/2.0.2/ScalaTest

**Comment by mayah** [comment]
play test で回ります。

**Comment by KengoTODA** [comment]
awesome.
