### ISSUE TITLE
前日通知DMが異常なタイミングで届いた

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#205]
https://twitter.com/mr_konn/status/108371350778937344<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=205</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
This seems invalid for now...
Let's close this issue. Feel free to reopen if the same error is happening still.
