### ISSUE TITLE
OpenJPAで参照型プロパティをnullに変更できない

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#208]
issue 153やissue 204の原因がこれ。
JPAEventDao#decode()やJPAEventDao#encode()で吸収しているが、根本解決を図りたい。影響範囲の大きな修正になるので注意。

参考：http://stackoverflow.com/questions/2453671/nullable-date-column-merge-problem

<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=208</p><hr/><h2>earlier comments</h2>
<p><strong>mayah@mayah.jp said, at 2012-01-12T14:14:37.000Z:</strong></p>

<p>bulk edit</p>

**Comment by mayah** [comment]
We don't use OpenJPA anymore.
INVALID
