### ISSUE TITLE
Manager comments should have +1 button

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#224]
It's marvelous, isn't it?<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=224</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
WONTFIX for now.
