### ISSUE TITLE
Should we add some codereview process?

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#236]
rietvelt will work well.<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=236</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
WONTFIX
