### ISSUE TITLE
Partake should be able to post a task, which will run in background.

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#250]
Some methods want to return InputStream.
Currently we create byte array, however stream should be created on the fly.
To achieve it, we should have a task posting system.<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=250</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
WONTFIX.
Play has this function.
