### ISSUE TITLE
Partake should have EventListener.

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#251]
We often want to do something an event happens, e.g. an event is created, an event is modified, a user is created...
We want to introduce a event listener, which can be registered to PartakeService.<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=251</p><hr/><h2>earlier comments</h2>

<p><strong>mayah@mayah.jp said, at 2012-01-12T14:15:23.000Z:</strong></p>

<p>bulk edit to Priority-P2</p>

**Comment by mayah** [comment]
WONTFIX
