### ISSUE TITLE
PartakeDataCopier to convert JPA to Postgres9

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#277]
It's coming the day that JPA dies...
For the X day, we should prepare PartakeDataCopier to convert data from JPA to Postgres9.

<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=277</p><hr/><h2>earlier comments</h2>
<p><strong>mayah@mayah.jp said, at 2012-01-30T06:24:18.000Z:</strong></p>
<p>Currently "Demo" event has event id "demo", which is not UUID, so it cannot be used in Postgres9DAO.
We should change demo id before copying data. Do not forget all data which uses eventId is affected by this change.

Also, we should have a redirect to a demo page from /events/demo.
</p>

**Comment by mayah** [comment]
これは beta2 への移行に伴い不要となった。close します。
