### ISSUE TITLE
Recheck licenses of third party libraries used in PARTAKE (2012 1H)

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#278]
It's time to recheck licenses of third party libraries used in PARTAKE.

For all libraries, we should check the following:
 (1) What license?
 (2) Do we have to show something to keep the license?
 (3) If we violate the licence, can we keep the license again? Or should we change the library to keep the license?

<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=278</p>

**Comment by KengoTODA** [comment]
Hello, contributors.
I've checked all of Java libraries, CSS libraries and JS libraries. And I found that [border-radius.htc](http://code.google.com/p/curved-corner/) is licensed by GPL. We aldo have a LGPL licensed library ([TinyMCE](http://www.tinymce.com/)), so I think that we have to stop using border-radius.htc (border-radius.htc says that user can use "content" under CC BY 3.0, but I think what we need is not "content" but "code").

@mayah, how do you think?

**Comment by mayah** [comment]
We haven't used border-radius.htc in beta2 (and beta3) anymore. We can
remove it safely.

**Comment by KengoTODA** [comment]
Good news. Thanks. I'll send a pull request to close this issue.
