### ISSUE TITLE
ROOTディレクトリ直下にprojectディレクトリなどを置きたい

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#299]
今はROOTディレクトリにPartakeディレクトリを掘っていますが、このディレクトリは要らないので中のファイルを直接ROOTに置きたいです。
他のプロジェクトやコンポーネントは別のリポジトリで管理すればいいのでわざわざ掘る必要がないし、こうした構成は慣習に沿っていない気がします。どう思われますか？

**Comment by mayah** [comment]
It's ok to me.

**Comment by mayah** [comment]
Fixed in
https://github.com/partakein/partake/commit/9516615b55855166cb8d99651533ea0c265c61c8#commitcomment-1525830

**Comment by KengoTODA** [comment]
Thanks!
