### ISSUE TITLE
Use JSON library provided from Play! framework instead of json-lib

### ISSUE THREAD

**Issue by mayah** [partakein/partake#316]
We would like to remove unnecessary dependency.

**Comment by KengoTODA** [comment]
ひと通り終わりました。既存テストは通ります。あとは手でテスト。
https://github.com/eller86/partake/tree/remove-jsonlib

**Comment by KengoTODA** [comment]
さすがにコンフリクトひどいのでこのブランチは捨てたほうがよさそうです。テスト回るようになってからゆっくり進めましょう。
