### ISSUE TITLE
Can't enroll any events

### ISSUE THREAD

**Issue by thagikura** [partakein/partake#332]
1. Click "参加申込" in event page.
2. Modal dialog doesn't appear.

Probably due to reasons below.

JSONObject.toString is escaped undesirebly in scala templates

"(double quotation) is escaped (&quot;) in scala templates.
So when JavaScript Object is retrieved like that, the result is not considered as JavaScript Object.

var enrollments = @{
    val userTicketMapJSON = new JSONObject()
    for (entry <- userTicketMap.entrySet()) {
        if (entry.getKey() != null && entry.getValue() != null)
            userTicketMapJSON.put(entry.getKey().toString(), JSONObject.fromObject(entry.getValue().toJSON()));
    }
    userTicketMapJSON.toString()
};

result JavaScript will be like this ->

var enrollments = {&quot;7d423342-5d64-42c5-92d9-aa8b14bc8537&quot;:{&quot;id&quot;:&quot;38d8467a-2054-4720-92c8-83b2f6c10581&quot;,&quot;userId&quot;:&quot;c489213e-3646-48e3-a07d-6c503eb32d15&quot;,&quot;ticketId&quot;:&quot;7d423342-5d64-42c5-92d9-aa8b14bc8537&quot;,&quot;eventId&quot;:&quot;75c3b6d7-cfe6-4e1a-ba95-3b64a3446964&quot;,&quot;comment&quot;:&quot;&#12424;&#12429;&#12375;&#12367;&#12362;&#39000;&#12356;&#12375;&#12414;&#12377;&#12290;&quot;,&quot;status&quot;:&quot;ENROLLED&quot;,&quot;modificationStatus&quot;:&quot;CHANGED&quot;,&quot;attendanceStatus&quot;:&quot;UNKNOWN&quot;,&quot;appliedAt&quot;:1341644685142,&quot;createdAt&quot;:1341644685142,&quot;modifiedAt&quot;:1341644685142}};

**Comment by mayah** [comment]
Maybe we can use @Html(), since JSON won't cause XSS here.

**Comment by thagikura** [comment]
That way works, thanks.
Will fix other parts as much as I can find.

var enrollments = @{
val userTicketMapJSON = new JSONObject()
for (entry <- userTicketMap.entrySet()) {
if (entry.getKey() != null && entry.getValue() != null)
userTicketMapJSON.put(entry.getKey().toString(), JSONObject.fromObject(entry.getValue().toJSON()));
}
<strong>Html</strong>(userTicketMapJSON.toString())
};

**Comment by mayah** [comment]
Could you send a patch if possible?

**Comment by thagikura** [comment]
Sure. sent a pull request.
