### ISSUE TITLE
メッセージ管理→リマインダーなどの送付状況　が表示されない

### ISSUE THREAD

**Issue by thagikura** [partakein/partake#339]
_show_manage_navigation.scala.html の json.notifications が定義されてないみたい。

routes の url 定義が実体と違うみたい

**Comment by thagikura** [comment]
./views/events/_show_manage_navigation.scala.html:        partake.event.getNotifications(eventId, 0, 10)
↓
./assets/javascripts/partake/partake.js:        getNotifications: function(eventId) {

return $.get('/api/event/getNotifications', arg);
↓
routes
GET     /api/event/getNotifications         in.partake.controller.api.event.GetNotificationsAPI.get()

あ、でも既に API 公開してる URL のはずなので
./assets/javascripts/partake/partake.js を直すべき

**Comment by thagikura** [comment]
routes の間違いだった
https://github.com/partakein/partake/wiki/%5BAPI%5D-Event-API

**Comment by mayah** [comment]
get は付けない方針にしたので、notifications が正しいです。
struts 版では直してるはずなので merge のし忘れかな……
