### ISSUE TITLE
Can't add additional tickets

### ISSUE THREAD

**Issue by thagikura** [partakein/partake#347]
Seems parameters of "applicationStart[]" are not sent to server.

from ticket edit page

**Comment by thagikura** [comment]
reproduce 
1. イベント編集を選択
2. チケットを編集を選択
3. 新しいチケットを追加　を選択
4. 任意のチケット名を入力
5. 編集終了 を押下
6. 保存 を押下

"パラメータの誤りがあります" が出て保存できない

**Comment by mayah** [comment]
Could you add some comments like
Fixed #347
in your commit message from now on?

It will close the related issue automatically if it's merged.

**Comment by thagikura** [comment]
Sure. From now on, will do so.
