### ISSUE TITLE
twitter consumer secretが公開されている

### ISSUE THREAD

**Issue by fukayatsu** [partakein/partake#355]
https://github.com/partakein/partake/blob/master/conf/twitter4j.properties

> https://dev.twitter.com/apps/YOUR_APP_ID/show
> OAuth settings
> Your application's OAuth settings. Keep the "Consumer secret" a secret. This key should never be human-readable in your  application.

とあり、テスト用だとしてもこのkeyとsecretを悪用することができるので、secretは公開すべきでないと思います。

**Comment by mayah** [comment]
誤って commit された直後に revoke されており、使用することはできません。
また、すでに #354 で fix されています。

**Comment by fukayatsu** [comment]
確認不足でした。すみません

**Comment by mayah** [comment]
情報ありがとうございました。言われなければおそらく放置したままで人々を混乱させてしまったはずです。
