### ISSUE TITLE
openid login error

### ISSUE THREAD

**Issue by kuwamura** [partakein/partake#366]
openid.ne.jpのアカウントでログインしようとしたら、エラーになり、ログインできませんでした。

**Comment by mayah** [comment]
多分 twitter id と結びつけされてない状態でログインしようとしたが、エラーメッセージがわかりにくいのが原因かと思います。

**Comment by mayah** [comment]
というか beta3 だとそもそも何も出ませんね。

**Comment by mayah** [comment]
I can login using Google account, but I cannot login mixi, or the other services.
That might be because I used http://127.0.0.1:9000 ?
I had a trouble with using my localhost IP before, but I'm not sure though...
