### ISSUE TITLE
application.secret must not be exposed

### ISSUE THREAD

**Issue by thagikura** [partakein/partake#370]
"application.secret"  must be secret, since it may be used for cryptographic functions ( Partake seems to not use it, though)
at least application-prod.conf.

**Comment by mayah** [comment]
Right. We have to conceal the real key.
Actually I have committed a patch to conceal it today. We can save PARTAKE specific configurations in DB now.

**Comment by mayah** [comment]
We would like to have a default value. If the default value is used in prod environment, we should reject to run the application. It's OK for dev environment or test environment.

**Comment by thagikura** [comment]
Having a default value seems fine. We gonna have a default value in the DB?

**Comment by mayah** [comment]
I think the default value should be something like "<<PLEASE SPECIFY SECRET HERE>>".

**Comment by mayah** [comment]
<<xmp>>

**Comment by mayah** [comment]
Oops.... I didn't know that the continuous < will be deleted in comments...
What I wanted say is '< <PLEASE SPECIFY YOUR SECRET HERE> >'

**Comment by mayah** [comment]
Try again:
<PLEASE SPECIFY YOUR SECRET HERE>

**Comment by mayah** [comment]
&lt;PLEASE SPECIFY YOUR SECRET HERE&rt;

**Comment by mayah** [comment]
&lt;&lt;PLEASE SPECIFY YOUR SECRET HERE&gt;&gt;
