### ISSUE TITLE
ハッシュタグ関連付け機能の消失

### ISSUE THREAD

**Issue by seizans** [partakein/partake#377]
イベント編集の、ハッシュタグ関連付けの項目がなくなった。
UI変更後。以前はあった。
前に作成したイベントでは関連付けが生きている様子：tweetするとそのハッシュタグが付記される。

**Comment by xuwei-k** [comment]
:+1: 

関連して

「ある(ハッシュタグが設定されていた古い)イベントをコピーして新しいイベントを作ろうとすると、古いハッシュタグを引き継いでしまい、なおかつそれを変更することも、削除することもできない」

という状態になってしまうみたいです。

http://partake.in/events/7211abc9-ebb8-4670-b912-3089dc5e0edd

![](http://cdn-ak.f.st-hatena.com/images/fotolife/x/xuwei/20121123/20121123120921.png)

**Comment by KengoTODA** [comment]
本日の更新で修正されました。9ヶ月近くかかってしまいご迷惑おかけしました。
