### ISSUE TITLE
検索ページのSearchボタンが効かない

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#378]
クリックしてもHTTPリクエストが飛ばない。Enterキー押下では検索できる。`type="button"`をsubmitに変更すればいいのではなかろうか。
http://partake.in/events/search

**Comment by KengoTODA** [comment]
単に変えただけではダメだった。POSTリクエストが送られるべきなのにGETリクエストが送られてしまう。

**Comment by mayah** [comment]
search は GET でも POST でも動いたほうがいいような

**Comment by mayah** [comment]
とはいえこれは merge されたので close します。

**Comment by KengoTODA** [comment]
GETはページまるまる更新してしまうリクエストだったのです。not Ajax。
