### ISSUE TITLE
APIのHTTPヘッダについて（確認）

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#380]
現在のpartake.in（beta2、Struts）はAPIに対してGETリクエストするとHTTPヘッダとして

```
Date: Sat, 21 Jul 2012 04:42:51 GMT
Transfer-Encoding: Identity
Content-Disposition: inline
Connection: Keep-Alive
Pragma: no-cache
Content-Type: json
Cache-Control: no-cache
Keep-Alive: timeout=15, max=99
```

を返しますが、localhost（beta3、play!、masterブランチ）では

```
Content-Length: 74
Content-Type: text/json; charset=utf-8
```

を返してきます。 GET /api/debug/echo?data=1 で確認。
Content-Typeの違いはともかく、キャッシュ周りの指定は現状維持が望ましいと思うのですがどうでしょうか？ドキュメントはこのへんを参照すればよさそうです。
- http://stackoverflow.com/questions/7547509/how-do-i-prevent-browser-caching-with-play

ちなみにContent-Typeは`application/json`が正しいそうです。いい機会なのでこちらも直してしまいましょう。
- http://stackoverflow.com/questions/477816/the-right-json-content-type

**Comment by mayah** [comment]
Needs patch

**Comment by KengoTODA** [comment]
やっていいかどうかだけ返事がほしかったです。
- キャッシュ周りの指定
- Content-Type

両方OKということでいいですか？

**Comment by mayah** [comment]
OK

**Comment by mayah** [comment]
僕の返事とか不要なので必要だと思ったらやってください。

**Comment by KengoTODA** [comment]
Pull request #381 solved this issue, but that request has no test code. I'll create it and close this issue later.
