### ISSUE TITLE
play clean test でAPIのテストが実行されない

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#382]
```
$ play test 2>&1 |grep -10 DebugAPI
...
[info] in.partake.controller.api.debug.DebugAPITest
[info] 
[info] 
[info] Total for test in.partake.controller.api.debug.DebugAPITest
[info] Finished in 0.633 seconds
[info] 0 tests, 0 failures, 0 errors
...
```

**Comment by KengoTODA** [comment]
Travis CI reproduced this problem.
see line #809 at http://travis-ci.org/#!/partakein/partake/builds/1919983

**Comment by KengoTODA** [comment]
CLASSPATHに異常があり`PartakeTestApp.createTwitterService`が正常終了しないことが一因と思われます。このメソッドを`return null;`に書き換えることでDebugAPITestが正常動作しました。なお書き換え前は以下の様なエラーが出ます（Mockitoの使い方は間違ってないように見えるのですが……）。

```
Misplaced argument matcher detected here:
-> at in.partake.app.PartakeTestApp.createTwitterService(PartakeTestApp.java:40)

You cannot use argument matchers outside of verification or stubbing.
Examples of correct usage of argument matchers:
    when(mock.get(anyInt())).thenReturn(null);
    doThrow(new RuntimeException()).when(mock).someVoidMethod(anyObject());
    verify(mock).someMethod(contains("foo"))
```

@mayah @hagikuratakeshi
1日粘りましたがSBT周りがよくわからないので、他の方に解決をお願いしたいです。すみません。
Travis CIで再現できることがわかっているので、そちらを最終確認に使ってください。

**Comment by mayah** [comment]
なんやら test 関連ライブラリを test scope にしているせいで色々おかしいことがわかりました。

**Comment by mayah** [comment]
a56f5d25de9669e9e17179d4dd477c215e09b2bc seems fixed this issue.

**Comment by mayah** [comment]
When you think this issue is not fixed, please feel free to reopen.

**Comment by KengoTODA** [comment]
我々のテストコードのスコープがtestじゃなかったとか？
うーん、解決とは言いがたいですが現象を抑えられたならOKでしょうか、明日Travis確認します。

**Comment by KengoTODA** [comment]
確認しました。

sbtに罪がないと仮定すると、依存しているライブラリがバージョン違いのMockitoを含んでしまっているんでしょう。以前はそんなことなかったので、新規に追加したライブラリを中心に疑いましょう。こちらで追います。

**Comment by KengoTODA** [comment]
とりあえず`play dependencies`ではそれらしいライブラリは見つかりませんでした……。
