### ISSUE TITLE
CIサーバからのメールが届かない

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#387]
Google GroupのMLが notifications@travis-ci.org からのメールを無視しているようで、グループのメンバーにメールが届きません。グループの設定の問題かと思うのですが、私は管理権限を持っていないので、確認・修正をお願いしたいです。

**Comment by mayah** [comment]
I've changed the PARTAKE DEV group settings so that anyone can post a message, though only members can view the messages.

**Comment by KengoTODA** [comment]
Thanks!
