### ISSUE TITLE
参加者数が100名を超えた場合に表示がおかしくなる

### ISSUE THREAD

**Issue by xuwei-k** [partakein/partake#399]
http://partake.in/events/9a5f18bf-ca0c-48cd-a050-8a564c1ab0d9

![bug_image](https://pbs.twimg.com/media/A1qXAAXCMAAckVa.png:large)

**Comment by KengoTODA** [comment]
ご報告感謝いたします。12月4日に予定しているアップデートで解消予定です。コード差分等は #411 をご覧ください。
