### ISSUE TITLE
Fail Whale

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#4]
When the server fails, fail whale should be displayed.<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=4</p><hr/><h2>earlier comments</h2>

<p><strong>shinyak@google.com said, at 2011-05-20T10:53:33.000Z:</strong></p>

<p>まあこれあのムサンガーくんのパラシュートの画像でいいんじゃなイカ？</p>

**Comment by mayah** [comment]
WONTFIX
