### ISSUE TITLE
Play! 2.0.3 cannot treat @import correctly

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#401]
Our build throws exception because Play framework cannot support CSS import.

```
[info] Set current project to PartakePlay (in build file:/Users/kengo/Documents/workspace/github/partake/)
[error] {file:/partake/}PartakePlay/*:play-copy-assets: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "split" of undefined (less-1.3.0.js#361)
[error] {file:/partake/}PartakePlay/compile:resources: org.mozilla.javascript.EcmaError: TypeError: Cannot call method "split" of undefined (less-1.3.0.js#361)
```

This problem was fixed a month ago, but they has no release with this patch. I think we have to wait the next release (maybe 2.0.4).
- https://github.com/playframework/Play20/pull/366

**Comment by KengoTODA** [comment]
Sorry my local Play! is `2.0.3-RC2` so I will try 2.0.3.

**Comment by KengoTODA** [comment]
My environment still has this problem... I will check travis tomorrow.

**Comment by mayah** [comment]
you should update git submodules. If not, I'm not sure why this error is caused...

**Comment by KengoTODA** [comment]
Thanks, I will try.

**Comment by KengoTODA** [comment]
OK, it works.
