### ISSUE TITLE
イベント検索画面にてSerchボタンをclickしても検索されない

### ISSUE THREAD

**Issue by shtaag** [partakein/partake#404]
キーボードreturnなら動く

**Comment by KengoTODA** [comment]
Current version works well.
I guess fa1d0db5 solved this problem, because [this change started to use click event to search](https://github.com/partakein/partake/blame/master/app/views/events/_search.scala.html).

**Comment by KengoTODA** [comment]
正常に反映されました。ありがとうございました。
