### ISSUE TITLE
offset option is not worked

### ISSUE THREAD

**Issue by tbaba** [partakein/partake#406]
I want to use PARTAKE Event API with maxNum and offset option, but I think that the offset option is not worked.

I got following resources, but same dataset are came back...

``` plain
GET http://partake.in/api/event/search?category=computer&maxNum=5&offset=1
GET http://partake.in/api/event/search?category=computer&maxNum=5&offset=6
```

**Comment by mayah** [comment]
The reason might be that PARTAKE was a bit old (today it's updated.)
If the problem still exists, please let us know again.

**Comment by tbaba** [comment]
Today I tried it again, and I got "Service Temporarily Unavailable".
You have already known this?

**Comment by mayah** [comment]
I'll ping operation team soon.

**Comment by mayah** [comment]
It seems the operation team has encountered some issues.

**Comment by mayah** [comment]
The operation team is saying that they are now fixing the issue. I hope it should be back soon.

**Comment by tbaba** [comment]
Thank you for your attention. The API is now working!
But I still have 'offset' problem... I think that the problem is not fixed yet.

**Comment by mayah** [comment]
OK. I'll check it later.

**Comment by KengoTODA** [comment]
Today PARTAKE had been upgraded, and this problem had been fixed in this version. Sorry for my delay.
