### ISSUE TITLE
イベントページでログインするとトップページへリダイレクトされてしまう

### ISSUE THREAD

**Issue by seizans** [partakein/partake#407]
イベントページでログインした場合、
以前はそのイベントページのままログイン状態になったが、
トップページへリダイレクトされるようになった。

以前の仕様の方が嬉しい。

**Comment by KengoTODA** [comment]
イベントページにいる時でも、#loginByTwitterFormにあるredirectURLが
`<input type="hidden" name="redirectURL" value="" />`
と空になっていることを確認。`@context.redirectURL.getOrElse("")`が常に空文字を返してしまっているようです。

**Comment by KengoTODA** [comment]
`AbstractPartakeAction#renderLoginRequired()`しか`PartakeActionContext#setRedirectURL()`を呼び出していないようなので、これが原因かと思います（EclipseがScalaコードをちゃんと拾えているか、やや自信なしです）。
未検証ですが`AbstractPartakeAction#render()`あたりで`#setRedirectURL()`を呼んでやるとか、PartakeActionContextImplのコンストラクタでredirectURLをセットしてしまうとか、このあたりで解決できるのではと思います。

**Comment by KengoTODA** [comment]
> AbstractPartakeAction#render()あたりで#setRedirectURL()を呼んでやるとか

この実装を用意してみました。近々検証します。
byte[]を受け取る`render()`はバイナリデータやらテキストファイルやらを生成するためのものなので、ここでredirectURLをセットする必要は無さそうです。

``` diff
diff --git a/app/in/partake/controller/action/AbstractPartakeAction.java b/app/in/partake/controller/action/AbstractPartakeAction.java
index 1b4a7d1..744dfe0 100644
--- a/app/in/partake/controller/action/AbstractPartakeAction.java
+++ b/app/in/partake/controller/action/AbstractPartakeAction.java
@@ -18,6 +18,7 @@ public abstract class AbstractPartakeAction extends AbstractPartakeController {
     // Renderers

     protected Result render(Content content) {
+        context().setRedirectURL(request().uri());
         return ok(content);
     }

```

**Comment by KengoTODA** [comment]
結局、最もシンプルな解として `AbstractPartakeController#redirectURL()` の実装変更を選択しました。redirectURLが設定されていないときはcurrentURLを代わりに使うように変更しています。 #425 の確認をお願いします。

**Comment by KengoTODA** [comment]
本日のアップデートで修正されていることを確認しました。ご報告ありがとうございました！
