### ISSUE TITLE
「受信メッセージ」ページの表示内容がおかしい

### ISSUE THREAD

**Issue by watsyasu** [partakein/partake#408]
ログイン後、「マイページ」→「受信メッセージ」
で「受信メッセージ」ページに遷移すると、
送信者、タイトル、受信日時が表示されるが、
ヘッダと表示内容が一致していない。

**Comment by KengoTODA** [comment]
ご報告ありがとうございます。本問題は #468 にて修正されます。次回のリリースをお待ちください。
