### ISSUE TITLE
twitterでアイコンを変更してもPartakeに反映されない

### ISSUE THREAD

**Issue by watsyasu** [partakein/partake#409]
twitterのプロフィールを編集し、アイコンを変更しても、partakeの表示が反映されない。
なお、partakeにログインすると、ログイン直後一瞬だけ変更後のアイコンが表示されるが、すぐに
もとのアイコンに置き換わり、その後ももとのアイコンが表示される。

また、参加したイベントの参加情報に表示されるアイコンも、変更後のアイコンにならない。

**Comment by mayah** [comment]
DB のアップデートに失敗している？

**Comment by KengoTODA** [comment]
本日のリリースで適用されました。アイコンの変更に追随できていることも確認済みです。ご報告＆パッチ作成に感謝します！
