### ISSUE TITLE
イベント検索テキストボックスでReturnしたときの挙動

### ISSUE THREAD

**Issue by seizans** [partakein/partake#413]
トップページのイベント検索テキストボックスでReturnすると

期待したい挙動：検索結果が表示される
現状の挙動：トップページに遷移する

**Comment by KengoTODA** [comment]
報告ありがとうございます。 aad1114031 で修正しました。
12月4日に予定しているアップデートで反映されます。

**Comment by KengoTODA** [comment]
正常に反映されました。ありがとうございました。
