### ISSUE TITLE
リンクURLが長いと途切れる

### ISSUE THREAD

**Issue by seizans** [partakein/partake#417]
イベント本文にアンカーするリンクURLが長いと途切れる。
例えば次のURLへのリンクが張れない。
http://partake.in/events/5ca0b9eb-10d3-437f-bdc2-712727d1d518

以下の1つ目のリンクを貼るつもりが、下のリンクになっているので、長いとかじゃないかもしれない。
http://partake.in/events/5ca0b9eb-10d3-437f-bdc2-712727d1d518
http://partake.in/5ca0b9eb-10d3-437f-bdc2-712727d1d518

**Comment by KengoTODA** [comment]
その他の事例：https://twitter.com/manu3da4/status/325867989251538945

**Comment by KengoTODA** [comment]
保存してイベント画面に行くと確かに `/events` が切れている。具体的に言うと、相対リンク（`../../eventId`）になっている。再度編集画面に行くと問題ないが、やっぱりここでも相対リンクになっている。

エディタが勝手に絶対リンクを相対リンクに変更していると予想。編集画面は `http://partake.in/events/edit/basic/5efd8fd9-db1a-4211-b148-3a0da0347b42` と、イベント画面比べて階層が深いので、こういう現象になるのだろう。設定あるかな？

**Comment by KengoTODA** [comment]
http://www.tinymce.com/tryit/url_conversion.php

ありました。ということでリクエスト送りましたのでよろしくお願いします。

**Comment by KengoTODA** [comment]
本日のリリースで修正されました。ご報告ありがとうございました。
