### ISSUE TITLE
「編集中」を察知してほしい

### ISSUE THREAD

**Issue by seizans** [partakein/partake#418]
「イベントを編集」に関して。

「イベント説明を編集」していて、「保存」をせずに「編成を終了」すると編集結果は失われる。
「保存」も「キャンセル」もしていない場合は警告してくれると嬉しい。

イベント説明が長くなると、「保存」ボタンが画面外に行く結果、
「編成を終了」ボタンが「保存」ボタンだと勘違いして押すことがよくある。

**Comment by KengoTODA** [comment]
本日の更新で対応できました。ご確認ください。
