### ISSUE TITLE
「関連イベント」の編集ができない

### ISSUE THREAD

**Issue by seizans** [partakein/partake#423]
確認したこと：
既に関連イベントが1つ登録されている状態で
「関連イベントを編集」
を押しても、
- 既に登録されているイベントの編集や削除ができない
- 新規に関連イベントを登録することができない

**Comment by KengoTODA** [comment]
JS エラーが出ています。

```
var relatedEventIds = [


        ff24c3ad-98b6-4fe3-b2be-68d220d6a866
Uncaught SyntaxError: Unexpected token ILLEGAL

];
```

再現するテストケース書けると良かったんですが、ちょっと現状だと複雑すぎそうですね。修正だけコミットしてプルリク送ります。

**Comment by KengoTODA** [comment]
この問題自体は本日の更新で修正されました。
関連する問題では #435 が残っています。
