### ISSUE TITLE
マイページのカレンダーで表示されるカレンダーURLにアクセスしても「リソースが見つかりませんでした」となる

### ISSUE THREAD

**Issue by yotchang4s** [partakein/partake#430]
カレンダーのURLを
http://partake.in/calendars/hogehoge.ics
 から
http://partake.in/calendars/hogehoge
に変えたらアクセスできたので、URLが誤っているようです。

**Comment by KengoTODA** [comment]
ご連絡いただきましてありがとうございました！次回のデプロイで修正が取り込まれることと思います。

**Comment by KengoTODA** [comment]
本日のアップデートで修正されていることを確認しました。ご報告ありがとうございました！
