### ISSUE TITLE
特定ユーザのイベントを生まれる前に消し去りたい

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#432]
あーこの人の情報はいいやーと思ったときにアンフォローする権利をユーザが所有してしかるべき。イベントがユーザの目に付く場所はトップページ、検索結果、Feed（RSS/iCal）など多岐にわたるので、検索時の条件とかじゃなくてユーザごとの設定として持つべきだろう。

あるいは「スパムを報告」機能を作って、投票が一定に達したらアカウントを無効化するとか。こっちのほうが実装は素直そう。

**Comment by seizans** [comment]
規約の禁止事項に「運営側が不適当と判断した行為」を追加することを提案したく思います。
柔軟な対応ができると思うので。

**Comment by KengoTODA** [comment]
一応、[それに近い記載](http://partake.in/termofuse)は今でもあります。

```
サービスの利用

    当社は、本サービスにおいて投稿されたイベントに関して、会員の許諾なく次の処理を行うことがあります。
        本サービスに投稿したイベントなどに関して、掲載を拒否すること、修正して掲載すること
```

手対応は現状でも可能ですが、機能で対応する方がシステム開発上は望ましい（魅力になる）というのと、手動削除は判断基準が不明確に見えた場合にユーザの不信感を招くという問題があるなと思っています。

イタチごっこになるというのも不安点ですが、これは機能で対応してもそんなに変わらないかもしれません。

**Comment by seizans** [comment]
なるほど。
であれば現状はまず手対応が妥当そうですね。

**Comment by KengoTODA** [comment]
ふむ、確かにまず動いてしまうのはありですね。ユーザで絞ってイベントを不可視化するとか。

ただ「本規約の違反」は現状ではない（という認識です）ので、ユーザの削除はちょっとグレーですね。過去のイベントを不可視化して、新しいイベントもバッチで不可視化していくとか、そのくらいが可能な限界かと。ひとまずは中の人に警告送るべきかもしれません。

**Comment by KengoTODA** [comment]
先週はちょっと時間取れませんでしたが、今週はじめから中の人とのコミュニケーションを行なっていこうと思います。最初は1〜2アカウントだけだったのに最近見たらかなり増えていて、割れ窓理論の正しさを感じています。

**Comment by KengoTODA** [comment]
連絡先がわかっている団体について、連絡を終了しました。アカウントをBANする機能を実装してもいいかとは思いますが、ひとまず対応を開始できる状態です。

**Comment by mayah** [comment]
> ところで、APIってトランザクション管理はTransaction抽象クラスに任せていいんですよね？

これって、本当は anonymous function みたいにしたかったんですが、java ではうまくいかず、あまり美しくない実装になっています。
どちらかというと、java の美しさを捨てて、scala 化しやすいように作った、という。

> たまにCOMMITが遅れているのではないかと思わせる挙動を見せることがあるのですが……。

transaction は auto commit off なので、抜けないとコミットされませんが、それぐらいしか思いつきません。
