### ISSUE TITLE
「関連するイベント」を保存したあとで、関連イベントの一覧が表示されない。

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#435]
サーバサイドの実装（ModifyAPI.java）は

``` java
        ObjectNode obj = new ObjectNode(JsonNodeFactory.instance);
        obj.put("eventId", eventId);
        return renderOK(obj);
```

なのに、JavaScript（_edit_side_information.scala.html）は

``` javascript
    .done(function (json) {
        ...
        if (!json.relatedEvents)
            return;
```

になっている。この`(!json.relatedEvents)`は常に真なので、関連イベントの一覧が常に表示されないことになる。

なんか修正の影響範囲が大きそうです。

**Comment by KengoTODA** [comment]
[Modify APIの仕様](https://github.com/partakein/partake/wiki/%5BAPI%5D-Event-API)では、レスポンスは「なし」になっているようです。つまり今の実装は仕様に準拠していないということですね。

これを「なし」から「変更されたイベント」に変えることで、JavaScript側の実装は再利用できると思います。
現在の挙動に頼った（仕様に頼っていない）APIユーザがいたらちょっとまずいのですが、少なくとも私は知らないです。いたら、バージョンをURLに含めることで影響を抑えましょう。

**Comment by mayah** [comment]
変更されたイベントに変えるべきだと思います。
なしになっていることに依存している人はいないと思って良いかと……。

**Comment by KengoTODA** [comment]
本日のリリースで修正されました。
