### ISSUE TITLE
開催日時の変更後の表示が一時的におかしい

### ISSUE THREAD

**Issue by seizans** [partakein/partake#444]
イベント編集 -> イベントを編集 -> 日時を編集
から、日時を変更し、保存を押す。
すると変更前の日時が表示される。
編集を終了 すると、糸通、変更後の日程が表示されるようになる。

**Comment by KengoTODA** [comment]
#435 と同じ、APが返すJSONがJSの期待するものと違うことに由来するものです。AP実装の見直しが要るかも。

**Comment by KengoTODA** [comment]
本日のリリースで修正されました。
