### ISSUE TITLE
Fix invalid HTML

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#451]
Our HTML is invalid, it would make trouble like X-browser problem.
- [index.html](http://html5.validator.nu/?doc=http%3A%2F%2Fpartake.in%2F&showsource=yes)
- [event page](http://html5.validator.nu/?doc=http%3A%2F%2Fpartake.in%2Fevents%2F77252e4a-045e-43af-b478-f8d8a949e94d&showsource=yes)

**Comment by mayah** [comment]
I think we can remove
&lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8"&gt;
&lt;meta http-equiv="Content-Script-Type" content="text/javascript"&gt;
these two lines.

Instead, we would like to have
&lt;meta charset="utf-8"&gt;
