### ISSUE TITLE
開催日時の変な挙動

### ISSUE THREAD

**Issue by seizans** [partakein/partake#460]
開始日時にフォーカス当てると、開始日次の月のカレンダーが表示されるが、
終了日時にフォーカス当てると、今月(現在日次の月)のカレンダーが表示される。
開始日時と終了日時で動作が違うことが奇妙に感じる。

またその結果としてだと思うが、
終了日時にフォーカスを当てて表示されたカレンダーで、
次の月を表示させると、終了日時が来月の今日になる、という挙動になる。

期待する動きとしては、
カレンダーでは日付を選択するまでは入力日付が変わらない、という動作でしょうか。

あと、開始日時でも終了日時でも
カレンダーで次の月に行こうとすると、
「保存されていない変更があります」ダイアログが出る。
ダイアログの意図と違うと思うので、出ないべきだと思います。
確認ブラウザは Chrome。

**Comment by KengoTODA** [comment]
pull requestよろしくお願いします！
