### ISSUE TITLE
編集者を追加・削除の変な挙動

### ISSUE THREAD

**Issue by seizans** [partakein/partake#461]
「編集者を追加・削除」において、
追加・削除をした後で「保存」を押すと、
その変更がなされなかったような表示(追加・削除前と同じ編集者の構成)になる。

ただし、「編集を終了」なりすると、行った追加・削除は実は有効だったとわかる。

**Comment by KengoTODA** [comment]
コード読んでいませんが、 #435 と同じ問題だと推測します。ちょっと根が深いですね。

**Comment by mayah** [comment]
Hmm...

**Comment by KengoTODA** [comment]
本日のリリースで修正されました。
