### ISSUE TITLE
チケットの保存ボタンの挙動

### ISSUE THREAD

**Issue by seizans** [partakein/partake#462]
今の挙動：
チケット編集で、
チケット枚数を編集した後、
保存ボタンを押すためにフォーカスをチケット枚数から外す必要がある。
(チケット枚数にフォーカスが当たっていると保存ボタンが押せない)

意図する挙動はたぶん、チケット枚数にフォーカスが当たっていても保存ボタンを押せる。

Chrome で確認。

**Comment by KengoTODA** [comment]
コード読んでませんが、changeイベント使えば行けそうな気がします。

**Comment by KengoTODA** [comment]
`change`と`keydown`を合わせてみましたが、今度はinputをクリックしただけで（フォーカスしただけで）ボタンが有効化するようになりました。あまり良い改善ではないと思いますが、どうしましょう？
- この実装で良しとする
- 常にボタンを有効化する
- 各inputごとに「前の値」を覚えておいて、keydown/changeイベント発火時にそれと照らし合わせる

個人的には「常にボタンを有効化する」で充分ではないかと思っています。

参考：http://stackoverflow.com/questions/574941/best-way-to-track-onchange-as-you-type-in-input-type-text

**Comment by mayah** [comment]
常に有効でいいと思います。

**Comment by KengoTODA** [comment]
本日の更新で partake.in に適用されました。ご報告ありがとうございました。
