### ISSUE TITLE
イベント説明にリンクを挿入する際、最終的にtarget属性が削除される

### ISSUE THREAD

**Issue by mazgi** [partakein/partake#476]
## 現象

TinyMCEの問題かもしれませんが、イベント説明でリンクを挿入した際、最終的にtarget属性が削除されてしまいました。
### 再現手順
1. イベント説明でリンクを挿入し「新しいウインドウで開く」を選択し更新ボタンを押す(添付画像1枚目)
2. 「保存」ボタンを押すとtarget属性が反映される(添付画像2枚目)
3. 「編集を終了」ボタンを押すとtarget属性が削除される(添付画像3枚目)

なお「同じウインドウで開く」を選択しても同じ現象が発生しました。
### スクリーンショット

1枚目: 編集画面でtargetを設定  
![image_01](https://f.cloud.github.com/assets/194222/659389/0c4aee9c-d690-11e2-8341-78a40793182f.png)

2枚目: 「保存」ボタン押下後、「編集を終了」ボタン押下前  
![image_02](https://f.cloud.github.com/assets/194222/659390/172276d2-d690-11e2-95c6-5f72db72790f.png)

3枚目: 「編集を終了」ボタン押下後  
![image_03](https://f.cloud.github.com/assets/194222/659391/205f50bc-d690-11e2-89e4-5dd40f3ffbb0.png)
### 発生したページ

[第一回　ゆるふわHaskell入門会](http://partake.in/events/f3fccb40-2017-432e-890e-5d21326c330c)
### 発生したWebブラウザ
- Mac OSX 10.8.4 上の下記ブラウザで発生しました
  - Safari Version 6.0.5 (8536.30.1)
  - Chrome Version 27.0.1453.110
  - Firefox 19.0

**Comment by KengoTODA** [comment]
おはようございます。詳細にわたるご報告ありがとうございました。

TO 開発者:

[現在の設定](https://github.com/partakein/partake/blob/0e77fc0bd8bfc2c975b7e0c60740447d017643cb/app/views/events/edit_basic.scala.html#L479)を見る限りそれらしい設定は明示されていないようです。ドキュメントを見た感じでは[valid_elements](http://www.tinymce.com/wiki.php/configuration:valid_elements)が関係していそうですので、これを触ってみます。

**Comment by mayah** [comment]
HTML から script などを取り除く処理をしている箇所で削除されていると思います。tinymce ではないと予想。

**Comment by KengoTODA** [comment]
なるほど確かにそのとおりで、antisamyでした。target指定するのはTinyMCEの機能ですから、TinyMCEとケンカしたとは考えにくかったですね。

**Comment by KengoTODA** [comment]
本日の更新で partake.in に適用されました。ご報告ありがとうございました。

**Comment by mazgi** [comment]
ご対応ありがとうございましたー！
