### ISSUE TITLE
ログインできない

### ISSUE THREAD

**Issue by cutsea110** [partakein/partake#495]
昨日からtwitterアカウントによるログインができなくなりました.
毎日ログインしていたわけではないのでいつからか正確なところは把握していません.
twitterアカウントでログインを選択すると以下のエラー画面が表示されます.

---

サーバーエラーが発生しました
ご迷惑をおかけしております。サーバーの内部でエラーが発生しました。

次のような原因が考えられます。

twitter が不安定であるなどの理由で、twitter へのリクエストが正常に動作しなかった。
データベースとの接続がうまくいっていない。
操作をやり直してみてください。それでもエラーが発生する場合 twitter にて @partakein までお問い合わせください。

もしくは、Issue Tracker へ登録していただいてもかまいません。(日本語でも英語でもかまいません。)

エラー詳細 (上級者向け / 管理者向け)
このエラーは、ユーザーからのリクエストを正常に受け付けたが処理中にサーバー内部で予期せぬエラーが発生した場合に発生します。

サーバー内部のエラー詳細は以下の通りでした。

エラーコード
TWITTER_OAUTH_ERROR
エラーメッセージ
twitter との接続に失敗しました。
トップに戻る

**Comment by KengoTODA** [comment]
メンテナンスを行い、問題を解消しました。報告いただきありがとうございました。

本issueは根本問題（#495）を解決した後にクローズします。
