### ISSUE TITLE
Musangaのぬいぐるみ

### ISSUE THREAD

**Issue by KengoTODA** [partakein/partake#64]
Musangaのぬいぐるみ

<p>Migrated from http://code.google.com/p/partakein/issues/detail?id=64</p><hr/><h2>earlier comments</h2>
<p><strong>kawanaka.shinya said, at 2011-01-26T14:46:16.000Z:</strong></p>

<p>T-shirt 作りましょう。</p>

**Comment by mayah** [comment]
WONTFIX
